export const menuactivo = [
  { name: 'Home',
    url: 1,
    state: true,
    icon: 'home-outline',
    image: '',
  },
  { name: 'Home',
    url: 1,
    state: false,
    icon: 'home-outline',
    image: '',
  },
  { name: 'Nueva Lista',
    url: 5,
    state: true,
    icon: 'add-circle',
    image: '',
  },
  { name: 'Perfil',
    url: 2,
    state: true,
    image: '',
  },
    { name: 'Inscripcion',
    url: 4,
    state: false,
    icon:'person-add-outline',
    image: '',
  },
  { name: 'Login',
    url: 3,
    state: false,
    icon: 'person-circle-outline',
    image: '',
  },
];
